<?php

    /*EN ESTE ARCHIVO SE DECLARAN LAS CONSTANTES PARA PODER CONECTARNOS A LA DB, NECESITAMOS 3 PARÁMETROS, EL USUARIO, LA CONTRASEÑA Y
    LA DIRECCION DEL SERVIDOR*/
    define('USER', 'sam');//CAMBIA usuario POR EL NOMBRE DEL USUARIO QUE CREASTE EN ORACLE
    define('PASS', 'master01');//CAMBIA pass POR LA CONTRASEÑA DEL USUARIO DE ORACLE
    define('SERVER', 'localhost/XE');


